{% set version = "3.11.0" %}

package:
  name: go-shfmt
  version: {{ version }}

source:
  url: https://github.com/mvdan/sh/archive/v{{ version }}.tar.gz
  sha256: 69aebb0dd4bf5e62842c186ad38b76f6ec2e781188cd71cea33cb4e729086e94

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - gosh --help
    - shfmt --help

about:
  home: https://github.com/mvdan/sh
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - license-files_gosh/
    - license-files_shfmt/
  summary: A shell parser, formatter, and interpreter. Supports POSIX Shell, Bash, and mksh
  description: |
    shfmt is a simple, yet powerful, formatter for shell scripts.
    It supports multiple shell dialects such as: POSIX Shell, Bash & mksh.
    shfmt is also highly configurable and can format your code in
    several fashion & conventions, for example take a look at
    Google's bash styling: https://google.github.io/styleguide/shell.xml
  dev_url: https://github.com/mvdan/sh

extra:
  recipe-maintainers:
    - danielnachun
    - roeey777
